version: '3.5'
services:
  db:
    image: postgres:9.6.20
    container_name: db
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asdf